# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: task.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'task.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntask.proto\x12\x04task\"1\n\x0bTaskRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"\x1f\n\x0cTaskResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x14\n\x06TaskId\x12\n\n\x02id\x18\x01 \x01(\t\"6\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"%\n\x08TaskList\x12\x19\n\x05tasks\x18\x01 \x03(\x0b\x32\n.task.Task\"\x07\n\x05\x45mpty2\x90\x01\n\x0bTaskService\x12\x30\n\x07\x41\x64\x64Task\x12\x11.task.TaskRequest\x1a\x12.task.TaskResponse\x12#\n\x07GetTask\x12\x0c.task.TaskId\x1a\n.task.Task\x12*\n\x0bGetAllTasks\x12\x0b.task.Empty\x1a\x0e.task.TaskListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'task_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASKREQUEST']._serialized_start=20
  _globals['_TASKREQUEST']._serialized_end=69
  _globals['_TASKRESPONSE']._serialized_start=71
  _globals['_TASKRESPONSE']._serialized_end=102
  _globals['_TASKID']._serialized_start=104
  _globals['_TASKID']._serialized_end=124
  _globals['_TASK']._serialized_start=126
  _globals['_TASK']._serialized_end=180
  _globals['_TASKLIST']._serialized_start=182
  _globals['_TASKLIST']._serialized_end=219
  _globals['_EMPTY']._serialized_start=221
  _globals['_EMPTY']._serialized_end=228
  _globals['_TASKSERVICE']._serialized_start=231
  _globals['_TASKSERVICE']._serialized_end=375
# @@protoc_insertion_point(module_scope)
